import { styleTags, tags as t } from '@lezer/highlight'

export const klipperConfigHighlighting = styleTags({
    ImportKeyword: t.keyword,
    Import: t.keyword,
    Parameter: t.keyword,
    ConfigBlock: t.namespace,
    BlockType: t.namespace,
    Identifier: t.attributeName,

    String: t.string,
    Boolean: t.string,
    Number: t.number,
    Cords: t.number,
    Pin: t.atom,
    VirtualPin: t.atom,
    Path: t.className,
    File: t.className,
    FilePath: t.className,

    AutoGenerated: t.name,
    Comment: t.lineComment,
})
